name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Docker Compose files
      run: |
        echo "🔍 Validating Docker Compose files..."
        for week in week1-xray week2-builder week3-optimizer week4-detective week5-architect; do
          compose_file="learning-app/labs/${week}/docker-compose.yml"
          if [ -f "$compose_file" ]; then
            echo "Checking ${week}..."
            docker-compose -f "$compose_file" config > /dev/null
          fi
        done
        echo "✅ All compose files valid"
    
    - name: Check shell scripts
      run: |
        echo "🔍 Checking shell scripts..."
        find . -name "*.sh" -type f -exec bash -n {} \;
        echo "✅ All shell scripts valid"
    
    - name: Security scan
      run: |
        echo "🔍 Running security checks..."
        # Check for hardcoded secrets
        if grep -r "password\|secret\|key" --include="*.yml" --include="*.yaml" learning-app/labs/ | grep -v "LICENSE_KEY"; then
          echo "⚠️  Warning: Possible hardcoded secrets found"
        fi
        echo "✅ Security check complete"

  test-terminal-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Test terminal server
      run: |
        cd learning-app/server
        npm ci
        npm test || echo "No tests defined yet"
