# kafka-config.yml - Configuration for nri-kafka integration
integrations:
  - name: nri-kafka
    env:
      # Cluster identification
      CLUSTER_NAME: "kafka-xray-lab"
      KAFKA_VERSION: "2.6+"
      
      # Discovery configuration
      AUTODISCOVER_STRATEGY: "bootstrap"
      BOOTSTRAP_BROKER_HOST: "localhost"
      BOOTSTRAP_BROKER_KAFKA_PORT: 9092
      BOOTSTRAP_BROKER_JMX_PORT: 9999
      
      # Collection toggles
      COLLECT_BROKER_TOPIC_DATA: "true"
      COLLECT_BROKER_TOPIC_METRICS_V2: "false"
      COLLECT_TOPIC_SIZE: "false"
      CONSUMER_OFFSET: "false"
      
      # Filtering (optional)
      # TOPIC_LIST: '["test-topic", "important-topic"]'
      # TOPIC_REGEX: "prod-.*"
      
      # JMX Configuration
      JMX_HOST: "localhost"
      JMX_PORT: 9999
      # JMX_USER: "jmx_user"
      # JMX_PASS: "jmx_password"
      
      # SSL/TLS Configuration (if needed)
      # JMX_SSL: "true"
      # JMX_KEYSTORE: "/path/to/keystore"
      # JMX_KEYSTORE_PASSWORD: "password"
      # JMX_TRUSTSTORE: "/path/to/truststore"
      # JMX_TRUSTSTORE_PASSWORD: "password"
      
      # Kafka SASL Configuration (if needed)
      # SASL_MECHANISM: "PLAIN"
      # SASL_USERNAME: "kafka_user"
      # SASL_PASSWORD: "kafka_password"
      
      # Debugging
      LOG_LEVEL: "info"  # Change to "debug" for troubleshooting
      
    interval: 30s
    labels:
      environment: "development"
      team: "platform"
