# New Relic Infrastructure - Kafka Integration Configuration
# This configuration enables comprehensive Kafka monitoring

integrations:
  - name: nri-kafka
    env:
      # Cluster name for grouping metrics
      CLUSTER_NAME: 'kafka-observability-lab'
      
      # Autodiscovery strategy - bootstrap is recommended
      AUTODISCOVER_STRATEGY: bootstrap
      
      # Bootstrap broker for discovery
      BOOTSTRAP_BROKER_HOST: kafka
      BOOTSTRAP_BROKER_KAFKA_PORT: 9092
      BOOTSTRAP_BROKER_JMX_PORT: 9999
      
      # JMX configuration
      DEFAULT_JMX_USER: ''
      DEFAULT_JMX_PASSWORD: ''
      
      # Collection intervals
      PRODUCER_OFFSET: true
      CONSUMER_OFFSET: true
      
      # Topic configuration
      TOPIC_MODE: all  # Options: all, none, list
      # TOPIC_LIST: 'test-events,orders,payments'  # If using list mode
      
      # Consumer group monitoring
      COLLECT_CONSUMER_LAG: true
      
      # Broker configuration
      COLLECT_BROKER_TOPIC_DATA: true
      COLLECT_BROKER_TOPIC_PARTITION_DATA: true
      
      # Zookeeper configuration (for older Kafka versions)
      ZOOKEEPER_HOSTS: '[{"host": "zookeeper", "port": 2181}]'
      
      # TLS/SSL configuration (if needed)
      TLS_ENABLED: false
      # TLS_CA_FILE: /path/to/ca.crt
      # TLS_CERT_FILE: /path/to/cert.crt
      # TLS_KEY_FILE: /path/to/key.key
      # TLS_INSECURE_SKIP_VERIFY: false
      
      # SASL configuration (if needed)
      SASL_MECHANISM: 'PLAIN'
      # SASL_USERNAME: ''
      # SASL_PASSWORD: ''
      
      # Advanced settings
      CONSUMER_GROUP_REGEX: '.*'
      TOPIC_REGEX: '.*'
      TOPIC_BUCKET_SIZE: 150
      
    interval: 30s
    
    # Inventory configuration
    inventory_source: config/kafka
    
    # Labels for filtering in New Relic
    labels:
      env: lab
      purpose: learning
      week: "1"
      exercise: kafka-metrics

# Custom attributes for all metrics from this integration
custom_attributes:
  kafka_version: "7.5.0"
  deployment_type: "docker"
  learning_module: "xray-vision"